ktor:
  deployment:
    port: "$PORT:8080"
  application:
    modules:
      - me.kuku.telegram.extension.PushExtensionKt.push
      - me.kuku.telegram.config.KtorConfigKt.config
  mongo:
    uri: "$MONGO_URI:mongodb://172.17.0.1:27017"
    database: "$MONGO_DATABASE:tg"
  telegram:
    modules:
      - me.kuku.telegram.extension.CommentExtensionKt.comment
      - me.kuku.telegram.context.ContextKt.handleReturnButton
      - me.kuku.telegram.context.WaitNextMessageKt.waitMessage
      - me.kuku.telegram.context.WaitNextMessageKt.ss
      - me.kuku.telegram.context.WaitNextMessageKt.clear
      - me.kuku.telegram.extension.ConfigExtensionKt.config
      - me.kuku.telegram.extension.ConfigExtensionKt.positiveEnergyConfig
      - me.kuku.telegram.extension.DeleteExtensionKt.delete
      - me.kuku.telegram.extension.DeleteExtensionKt.deleteOperate
      - me.kuku.telegram.extension.ErrorHandlerKt.ss
      - me.kuku.telegram.extension.ErrorHandlerKt.re
      - me.kuku.telegram.extension.IndexExtensionKt.start
      - me.kuku.telegram.extension.LogExtensionKt.logShow
      - me.kuku.telegram.extension.LogExtensionKt.logSwitch
      - me.kuku.telegram.extension.OciExtensionKt.ociAbility
      - me.kuku.telegram.extension.OciExtensionKt.oci
      - me.kuku.telegram.extension.OciExtensionKt.operate
      - me.kuku.telegram.extension.OciExtensionKt.operateInstance
      - me.kuku.telegram.extension.OtherExtensionKt.other
      - me.kuku.telegram.extension.OtherExtensionKt.other
      - me.kuku.telegram.extension.PushExtensionKt.push
      - me.kuku.telegram.extension.PushExtensionKt.pushCallback
      - me.kuku.telegram.extension.SwitchExtensionKt.switch
      - me.kuku.telegram.extension.SwitchExtensionKt.switchCallback
      - me.kuku.telegram.extension.ToolExtensionKt.queryYgoCard
      - me.kuku.telegram.extension.ToolExtensionKt.tool
      - me.kuku.telegram.extension.ToolExtensionKt.loLiCon
      - me.kuku.telegram.extension.ToolExtensionKt.dyna
      - me.kuku.telegram.extension.UpdateExtensionKt.update
      - me.kuku.telegram.extension.ExecExtensionKt.exec
      - me.kuku.telegram.extension.ExecExtensionKt.baiduExec
      - me.kuku.telegram.extension.ExecExtensionKt.biliBiliExec
      - me.kuku.telegram.extension.ExecExtensionKt.hostLocExec
      - me.kuku.telegram.extension.ExecExtensionKt.kuGouExec
      - me.kuku.telegram.extension.ExecExtensionKt.miHoYoExec
      - me.kuku.telegram.extension.ExecExtensionKt.netEaseExec
      - me.kuku.telegram.extension.ExecExtensionKt.stepExec
      - me.kuku.telegram.extension.ExecExtensionKt.weiboExec
      - me.kuku.telegram.extension.ExecExtensionKt.douYuExec
      - me.kuku.telegram.extension.ExecExtensionKt.smZdm
      - me.kuku.telegram.extension.ExecExtensionKt.aliDrive
      - me.kuku.telegram.extension.ExecExtensionKt.nodeSeekExec
      - me.kuku.telegram.extension.ExecExtensionKt.glaDosExec
      - me.kuku.telegram.extension.ExecExtensionKt.iqyExec
      - me.kuku.telegram.extension.ExecExtensionKt.eCloudExec
      - me.kuku.telegram.extension.LoginExtensionKt.login
      - me.kuku.telegram.extension.LoginExtensionKt.baiduLogin
      - me.kuku.telegram.extension.LoginExtensionKt.biliBiliLogin
      - me.kuku.telegram.extension.LoginExtensionKt.douYu
      - me.kuku.telegram.extension.LoginExtensionKt.hostLocLogin
      - me.kuku.telegram.extension.LoginExtensionKt.huYaLogin
      - me.kuku.telegram.extension.LoginExtensionKt.kuGouLogin
      - me.kuku.telegram.extension.LoginExtensionKt.miHoYoLogin
      - me.kuku.telegram.extension.LoginExtensionKt.netEase
      - me.kuku.telegram.extension.LoginExtensionKt.xiaomiStepLogin
      - me.kuku.telegram.extension.LoginExtensionKt.weiboLogin
      - me.kuku.telegram.extension.LoginExtensionKt.twitterLogin
      - me.kuku.telegram.extension.LoginExtensionKt.pixivLogin
      - me.kuku.telegram.extension.LoginExtensionKt.smZdmLogin
      - me.kuku.telegram.extension.LoginExtensionKt.aliDriveLogin
      - me.kuku.telegram.extension.LoginExtensionKt.leiShenLogin
      - me.kuku.telegram.extension.LoginExtensionKt.nodeSeekLogin
      - me.kuku.telegram.extension.LoginExtensionKt.gloDosSign
      - me.kuku.telegram.extension.LoginExtensionKt.iqyLogin
      - me.kuku.telegram.extension.LoginExtensionKt.eCloudLogin
      - me.kuku.telegram.extension.LoginExtensionKt.linuxDoLogin
      - me.kuku.telegram.extension.OtherPushExtensionKt.otherPush
      - me.kuku.telegram.extension.OtherPushExtensionKt.otherPushCallback
      - me.kuku.telegram.extension.ManagerExtensionKt.manager
      - me.kuku.telegram.extension.ManagerExtensionKt.baiduManager
      - me.kuku.telegram.extension.ManagerExtensionKt.biliBiliManager
      - me.kuku.telegram.extension.ManagerExtensionKt.douYuManager
      - me.kuku.telegram.extension.ManagerExtensionKt.huYaManager
      - me.kuku.telegram.extension.ManagerExtensionKt.hostLocManager
      - me.kuku.telegram.extension.ManagerExtensionKt.kuGouManager
      - me.kuku.telegram.extension.ManagerExtensionKt.miHoYoManager
      - me.kuku.telegram.extension.ManagerExtensionKt.netEaseManager
      - me.kuku.telegram.extension.ManagerExtensionKt.stepManager
      - me.kuku.telegram.extension.ManagerExtensionKt.weiboManager
      - me.kuku.telegram.extension.ManagerExtensionKt.twitterManager
      - me.kuku.telegram.extension.ManagerExtensionKt.pixivManager
      - me.kuku.telegram.extension.ManagerExtensionKt.smZdmManager
      - me.kuku.telegram.extension.ManagerExtensionKt.aliDriveManager
      - me.kuku.telegram.extension.ManagerExtensionKt.leiShenManager
      - me.kuku.telegram.extension.ManagerExtensionKt.nodeSeekManager
      - me.kuku.telegram.extension.ManagerExtensionKt.glaDosManager
      - me.kuku.telegram.extension.ManagerExtensionKt.iqyManager
      - me.kuku.telegram.extension.ManagerExtensionKt.eCloudManager
      - me.kuku.telegram.extension.ManagerExtensionKt.linuxDoManager
      - me.kuku.telegram.extension.SettingExtensionKt.setting
      - me.kuku.telegram.extension.SettingExtensionKt.blackSetting
      - me.kuku.telegram.extension.SettingExtensionKt.adminSetting
      - me.kuku.telegram.extension.SettingExtensionKt.url
      - me.kuku.telegram.extension.SettingExtensionKt.log
      - me.kuku.telegram.extension.SettingExtensionKt.updateLogSwitch
    cron:
      - me.kuku.telegram.scheduled.AliDriveScheduledKt.aliDriveSign
      - me.kuku.telegram.scheduled.AliDriveScheduledKt.lastDayReceive
      - me.kuku.telegram.scheduled.AliDriveScheduledKt.aliDriveTask
      - me.kuku.telegram.scheduled.AliDriveScheduledKt.receiveTodayTask
      - me.kuku.telegram.scheduled.AliDriveScheduledKt.finishDeviceRoom
      - me.kuku.telegram.scheduled.AliDriveScheduledKt.receiveDeviceRoom
      - me.kuku.telegram.scheduled.AliDriveScheduledKt.finishCard
      - me.kuku.telegram.scheduled.AliDriveScheduledKt.receiveCard
      - me.kuku.telegram.scheduled.AliDriveScheduledKt.clearRubbish
      - me.kuku.telegram.scheduled.BaiduScheduledKt.baiduSign
      - me.kuku.telegram.scheduled.BiliBiliScheduledKt.biliBiliSign
      - me.kuku.telegram.scheduled.BiliBiliScheduledKt.biliBiliLiveMonitor
      - me.kuku.telegram.scheduled.BiliBiliScheduledKt.biliBiliUserMonitor
      - me.kuku.telegram.scheduled.BotConfigScheduledKt.commitPush
      - me.kuku.telegram.scheduled.ConfigScheduledKt.positiveEnergyPush
      - me.kuku.telegram.scheduled.ConfigScheduledKt.xianBaoPush
      - me.kuku.telegram.scheduled.DouYuScheduledKt.douYu
      - me.kuku.telegram.scheduled.DouYuScheduledKt.titleChange
      - me.kuku.telegram.scheduled.DouYuScheduledKt.douYuSign
      - me.kuku.telegram.scheduled.DouYuScheduledKt.douYuPush
      - me.kuku.telegram.scheduled.DouYuScheduledKt.douYuPush
      - me.kuku.telegram.scheduled.ECloudScheduledKt.eCloudSign
      - me.kuku.telegram.scheduled.EpicScheduledKt.pushFreeGame
      - me.kuku.telegram.scheduled.GlaDosScheduledKt.glaDosSign
      - me.kuku.telegram.scheduled.HostLocScheduledKt.locPush
      - me.kuku.telegram.scheduled.HostLocScheduledKt.hostLocSign
      - me.kuku.telegram.scheduled.HuYaScheduledKt.huYa
      - me.kuku.telegram.scheduled.IqyScheduledKt.iqySign
      - me.kuku.telegram.scheduled.KuGouScheduledKt.kuGouSign
      - me.kuku.telegram.scheduled.LeiShenScheduledKt.leiShenRemind
      - me.kuku.telegram.scheduled.LinuxDoScheduledKt.linuxDoIndex
      - me.kuku.telegram.scheduled.LinuxDoScheduledKt.linuxDoPost
      - me.kuku.telegram.scheduled.MiHoYoScheduledKt.genShinSign
      - me.kuku.telegram.scheduled.MiHoYoScheduledKt.mysSign
      - me.kuku.telegram.scheduled.NetEaseScheduledKt.netEaseSign
      - me.kuku.telegram.scheduled.NetEaseScheduledKt.netEaseMusicianSign
      - me.kuku.telegram.scheduled.NetEaseScheduledKt.vipSign
      - me.kuku.telegram.scheduled.NodeSeekScheduledKt.nodeSeekSign
      - me.kuku.telegram.scheduled.NodeSeekScheduledKt.querySign
      - me.kuku.telegram.scheduled.PixivScheduledKt.pixivPush
      - me.kuku.telegram.scheduled.SmZdmScheduledKt.smZdmSign
      - me.kuku.telegram.scheduled.StepScheduledKt.stepModify
      - me.kuku.telegram.scheduled.TwitterScheduledKt.twitterPush
      - me.kuku.telegram.scheduled.V2exScheduledKt.v2exPush
      - me.kuku.telegram.scheduled.WeiboScheduledKt.weiboSign
      - me.kuku.telegram.scheduled.WeiboScheduledKt.weiboUserMonitor
    token: "$TELEGRAM_TOKEN:"
    creatorId: "$TELEGRAM_CREATOR_ID:0"
    proxyHost: "$TELEGRAM_PROXY_HOST:"
    proxyPort: "$TELEGRAM_PROXY_PORT:0"
    proxyType: "$TELEGRAM_PROXY_TYPE:direct"
    url: "$TELEGRAM_URL:"
    localPath: "$TELEGRAM_LOCAL_PATH:"
    api: "$TELEGRAM_API:"